[package]
name = "weei-client"
version = "0.1.0"
authors = ["chennyweei <cheneiweei@gmail.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
rmp-serde = "0.13.7"
pub_proto = {path="../pub_proto"}
