[package]
name = "pub_proto"
version = "0.1.0"
authors = ["chennyweei <cheneiweei@gmail.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
phf = { version = "0.7.24", features = ["macros"] }
phf_macros = "0.7.24"
